# Site settings
remote_theme:   chesterhow/tale
title:          IT in Wonderland
description:    "A Place to Discuss System Design, Startups, Management, and Other Wonders from the IT World."
baseurl:        ""
url:            "https://itinwonderland.com/"
in_username:    "zarrie"

# Google Analytics
google_analytics: G-Q0NZGL0CY3

# Author
author:
  name:         Viktor Ivanov
  url:          https://itinwonderland.com/
  email:        viktoriivanov@yahoo.com
  linkedin:     https://www.linkedin.com/in/zarrie/

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

